<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DELL-PC" name="testScript.Scenrio_Login" tests="3" failures="1" timestamp="29 Sep 2016 08:36:37 GMT" time="63.221" errors="0">
  <testcase name="Invalid_login" time="12.356" classname="testScript.Scenrio_Login"/>
  <testcase name="Valid_login" time="15.701" classname="testScript.Scenrio_Login">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	page not loaded expected [rediff] but found [rediff.com ! Books Online],
	failed as the expected was qtpworld2008  and actual is qtpworld2008 g expected [qtpworld2008] but found [qtpworld2008 g]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	page not loaded expected [rediff] but found [rediff.com ! Books Online],
	failed as the expected was qtpworld2008  and actual is qtpworld2008 g expected [qtpworld2008] but found [qtpworld2008 g]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testScript.Scenrio_Login.Valid_login(Scenrio_Login.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- Valid_login -->
  <testcase name="Invalid_login" time="35.164" classname="testScript.Scenrio_Login"/>
</testsuite> <!-- testScript.Scenrio_Login -->
