<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DELL-PC" name="testScript.Scenrio_Login" tests="3" failures="1" timestamp="26 Sep 2016 19:08:28 GMT" time="43.497" errors="0">
  <testcase name="Valid_login" time="15.395" classname="testScript.Scenrio_Login">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	page not loaded expected [rediff] but found [rediff.com ! Books Online],
	failed as the expected was qtpworld2008  and actual is qtpworld2008 g expected [qtpworld2008] but found [qtpworld2008 g]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	page not loaded expected [rediff] but found [rediff.com ! Books Online],
	failed as the expected was qtpworld2008  and actual is qtpworld2008 g expected [qtpworld2008] but found [qtpworld2008 g]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testScript.Scenrio_Login.Valid_login(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- Valid_login -->
  <testcase name="Invalid_login" time="13.826" classname="testScript.Scenrio_Login"/>
  <testcase name="Invalid_login" time="14.276" classname="testScript.Scenrio_Login"/>
</testsuite> <!-- testScript.Scenrio_Login -->
